#!/usr/bin/env python3
"""bin2c.py — emit a C header defining `payload` / `payload_len` from a blob.

Used by the stage-0 build so the stage-0 loader (src/stage0/stage0.c) can
embed the assembled PIC payload. Usage:  bin2c.py <in.bin> <out.h>
"""
import sys


def main() -> None:
    src, dst = sys.argv[1], sys.argv[2]
    data = open(src, "rb").read()
    rows = []
    for i in range(0, len(data), 16):
        rows.append("  " + ", ".join("0x%02x" % b for b in data[i:i + 16]))
    body = ",\n".join(rows)
    with open(dst, "w") as f:
        f.write("/* generated by tools/bin2c.py -- do not edit */\n")
        f.write("static const unsigned char payload[] = {\n")
        f.write(body)
        f.write("\n};\n")
        f.write("static const unsigned int payload_len = %d;\n" % len(data))


if __name__ == "__main__":
    main()
